### ISSUE TITLE
How to setup the required module?

### ISSUE THREAD

**Issue by finmackandal** [alibaba/system-register-tools#1]
Is it possible to load the required module after kernel was built?

Is there a repo for said module?

**Comment by wangrongwei** [comment]
Hi,
The module required by this tool has not been accepted by the upstream of linux kernel,  but you can get the patch from the following link:

https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2398458.html.

later, I will push the patch or source code of this module into this repo.
